baseURL = 'https://henryleecode23.github.io/'
languageCode = 'en-us'
title = 'hlc23 Blog'
theme = "PaperMod"

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 30

[params.profileMode]
enabled = true
title = "hlc23"
subtitle = "Nothing here."
imageUrl = "img/profile.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "Enter the content"

[[params.profileMode.buttons]]
name = "Blog"
url = "/posts/"

[[params.profileMode.buttons]]
name = "Categories"
url = "/categories/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/henryleecode23"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/h_lee_c23/"

[params] 
ShowBreadCrumbs = true    
# 展示文章所在目錄
ShowReadingTime = true    
# 展示閱讀時間
ShowShareButtons = true    
# 展示分享按鈕
ShowPostNavLinks = true    
# 本地其他文章連結

[params.cover]
linkFullImages = true    
# 點擊圖片後以全螢幕檢視
